# render.yaml
services:
  - type: web
    name: solar-irradiance-api
    env: python
    runtime: python-3.11.7
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
