# Jekyll configuration for Solar API Documentation with Chirpy theme
lang: en

# Site Settings
title: Solar Irradiance Forecast API
tagline: Fast, accurate solar irradiance data and forecasting for renewable energy applications
description: >-
  A FastAPI microservice for retrieving historical solar irradiance and weather data from NASA POWER, 
  and for forecasting solar irradiance using machine learning.

# URL settings
url: "https://oguzhansavas.github.io"
baseurl: "/solar_api"

# Social Links
github:
  username: oguzhansavas

social:
  # Change to your full name.
  name: Oguzhan Savas
  email: oguzhansavas359@gmail.com
  links:
    - https://twitter.com/oguzhansavas
    - https://github.com/oguzhansavas

# Site verification (optional)
google_site_verification: # fill in to your verification string

# Theme and appearance
remote_theme: cotes2020/jekyll-theme-chirpy

# Theme settings
theme_mode: # [light|dark], empty means the theme respects the system color mode preference

# Favicon settings
favicon: # path to the favicon, /assets/favicon.ico or /assets/img/favicons/

# Avatar settings  
avatar: # /assets/img/avatar.jpg

# Build settings
timezone: Europe/Amsterdam

permalink: /posts/:title/
# paginate: 10  # Disabled for documentation site

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-paginate  # Disabled for documentation site
  - jekyll-archives
  - jekyll-include-cache

# Jekyll Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false

# Analytics (optional)
google_analytics:
  id: # fill in your Google Analytics ID

# Comments (optional)
comments:
  active: # The global switch for posts comments, e.g., 'disqus'.

# Self-hosted static assets (optional)
assets:
  self_host:
    enabled: false

# PWA (optional)
pwa:
  enabled: false

# CDN endpoint (optional)
cdn: 

# Search settings
search:
  enabled: true

# Table of Contents
toc: true

# Custom variables for API documentation
api_version: "v1"
api_base_url: "https://solar-api.onrender.com"
example_lat: 52.3676
example_lon: 4.9041
example_location: "Amsterdam, Netherlands"

# Collections
collections:
  endpoints:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      toc: true
      comments: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      toc: true
      pin: false
      published: true
  - scope:
      path: ""
      type: "endpoints"
    values:
      layout: "page"
      toc: true
      comments: false

# Chirpy theme navigation tabs
tabs:
  - title: "Getting Started"
    url: "/getting-started/"
    icon: "fas fa-rocket"
  - title: "API Reference"  
    url: "/api-reference/"
    icon: "fas fa-book"
  - title: "Examples"
    url: "/examples/"
    icon: "fas fa-code"
  - title: "Coverage"
    url: "/coverage/"
    icon: "fas fa-globe"
  - title: "Support"
    url: "/support/"
    icon: "fas fa-life-ring"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - tools/
  - README.md
