# Jekyll configuration for Solar API Documentation with Just the Docs theme
lang: en

# Site Settings
title: Solar Irradiance Forecast API
tagline: Fast, accurate solar irradiance data and forecasting for renewable energy applications
description: >-
  A FastAPI microservice for retrieving historical solar irradiance and weather data from NASA POWER, 
  and for forecasting solar irradiance using machine learning.

# URL settings
url: "https://oguzhansavas.github.io"
baseurl: "/solar_api"

# Social Links
github:
  username: oguzhansavas

# Build settings
timezone: Europe/Amsterdam

# Theme configuration
remote_theme: "just-the-docs/just-the-docs"
plugins:
  - jekyll-remote-theme

# Just the Docs configuration
color_scheme: dark
search_enabled: true
heading_anchors: true

# Enable dark mode by default
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/oguzhansavas/solar_api"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false

# Custom variables for API documentation
api_version: "v1"
api_base_url: "https://solar-api.onrender.com"
example_lat: 52.3676
example_lon: 4.9041
example_location: "Amsterdam, Netherlands"

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - tools/
  - README.md
