# Jekyll configuration for GitHub Pages
title: Solar Irradiance Forecast API
description: A FastAPI microservice for retrieving historical solar irradiance and weather data from NASA POWER, and for forecasting solar irradiance using machine learning.
baseurl: "/solar_api"
url: "https://oguzhansavas.github.io"

# Theme configuration
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation menu
header_pages:
  - getting-started.md
  - api-reference.md
  - examples.md
  - coverage.md
  - support.md

# Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  endpoints:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "endpoints"
    values:
      layout: "endpoint"

# Custom variables
api_version: "v1"
api_base_url: "https://solar-api.onrender.com"
example_lat: 52.3676
example_lon: 4.9041
example_location: "Amsterdam, Netherlands"

# SEO
twitter:
  username: oguzhansavas
  card: summary_large_image

author:
  name: Oguzhan Savas
  email: oguzhansavas359@gmail.com

social:
  name: Solar Irradiance Forecast API
  links:
    - https://github.com/oguzhansavas/solar_api

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
